# Generated by Django 4.1.7 on 2023-03-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funE_app', '0002_user_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firts_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=12),
        ),
    ]
